[package]
name = "mdbook-rust"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Enhanced Rust support for MDBook"
keywords = ["mdbook", "rustbook"]
readme = "../../README.md"

[dependencies]
anyhow.workspace = true
indoc.workspace = true
itertools.workspace = true
mdbook.workspace = true
ra_ap_syntax.workspace = true
semver.workspace = true
serde_json.workspace = true
